/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
    "./lib/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: ["class"],
  theme: {
    extend: {
      fontFamily: {
        sans: ["Plus Jakarta Sans", "sans-serif"],
      },
      colors: {
        background: "#F8FAFC",
        surface: "#FFFFFF",
        "surface-muted": "#F1F5F9",
        "surface-subtle": "#F8FAFC",
        "surface-hover": "#F1F5F9",
        "text-primary": "#0F172A",
        "text-secondary": "#475569",
        "text-muted": "#64748B",
        "text-disabled": "#94A3B8",
        border: "#E2E8F0",
        "border-strong": "#CBD5E1",
        primary: "#2563EB",
        "primary-hover": "#1D4ED8",
        "primary-active": "#1E40AF",
        "primary-soft": "#EFF6FF",
        "primary-container": "#DBEAFE",
        secondary: "#0F172A",
        "on-primary": "#FFFFFF",
        teal: "#14B8A6",
        "teal-soft": "#CCFBF1",
        amber: "#F59E0B",
        "amber-soft": "#FEF3C7",
        success: "#16A34A",
        "success-soft": "#DCFCE7",
        error: "#DC2626",
        "error-soft": "#FEE2E2",
        "compass-blue": "#2563EB",
        "fresh-teal": "#14B8A6",
        "soft-amber": "#F59E0B",
        path: "#93C5FD",
        "path-active": "#2563EB",
        node: "#2563EB",
        "inverse-surface": "#0F172A",
        "inverse-text": "#F8FAFC",
      },
      borderRadius: {
        xs: "0.375rem",
        sm: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.25rem",
        "2xl": "1.5rem",
        "3xl": "2rem",
      },
      spacing: {
        base: "8px",
        gutter: "24px",
        "section-desktop": "128px",
        "section-tablet": "96px",
        "section-mobile": "72px",
        "margin-desktop": "80px",
        "margin-tablet": "40px",
        "margin-mobile": "20px",
      },
      maxWidth: {
        content: "1280px",
      },
      boxShadow: {
        subtle: "0 2px 8px rgba(15, 23, 42, 0.04)",
        card: "0 10px 25px -5px rgba(15, 23, 42, 0.06)",
        elevated: "0 20px 40px -10px rgba(15, 23, 42, 0.10)",
        floating: "0 24px 50px -12px rgba(15, 23, 42, 0.14)",
      },
      transitionDuration: {
        fast: "150ms",
        normal: "250ms",
        slow: "400ms",
      },
      transitionTimingFunction: {
        app: "cubic-bezier(0.2, 0.8, 0.2, 1)",
      },
      screens: {
        mobile: "480px",
        tablet: "768px",
        desktop: "1024px",
        wide: "1280px",
      },
    },
  },
  plugins: [],
}